### ISSUE TITLE
Float parse error on create

### ISSUE THREAD

**Issue by PlasmaHH** [VE3NEA/HeatMapView#2]
Hi, when trying to add a heat map from CSV I get the error "unable to generate heat map. Error '43700.52' is not a valid floating point value.

This is the fft bin size. Tried this on recent sdrsharp in Windows 10 on a German machine.

I would suspect whatever method is used to parse floats is expecting , instead of . As decimal separator.

PS I have limited online access at the moment, so of anything like the csv or screenshots are necessary this will have to wait

**Comment by VE3NEA** [comment]
You are right, on the German computers the decimal separator is a comma. Try replacing dots in your csv file with commas in a text editor.

**Comment by PlasmaHH** [comment]
This is unlikely to work as comma is the field separator.

Maybe it would be at least nice to have the plugin say that it doesn't work there

**Comment by VE3NEA** [comment]
Please try the new HeatMapGenerator.dll file, the problem should be fixed now.
