### ISSUE TITLE
Heatmap is not taking the available full space

### ISSUE THREAD

**Issue by psa-jforestier** [VE3NEA/HeatMapView#4]
When a heatmap is displayed, the heatmap window is not fully sized to the SDR# window.
See screen shot : the heat map could be expanded to the left (to be close to the "zoom" slider) and to the top (to be close to the wave window). The heatmap should be placed also on the purple lines I draw on the screenshot.
![Sans titre](https://user-images.githubusercontent.com/14594410/90644678-4ced8500-e235-11ea-8a0c-9848d88dddfc.png)

**Comment by VE3NEA** [comment]
I am unable to reproduce this, sorry.
